version: "3.9"

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile   # FIXED (case-sensitive)

    container_name: mini-sagar-ai-chatbot

    restart: unless-stopped

    ports:
      - "3001:3001"

    env_file:
      - .env

    environment:
      - NODE_ENV=production
      - PORT=3001
      - QDRANT_URL=http://qdrant:6333

    depends_on:
      - qdrant

    networks:
      - app-network
  qdrant:
    image: qdrant/qdrant:latest

    container_name: qdrant-db

    restart: unless-stopped

    expose:
      - "6333"

    volumes:
      - qdrant_storage:/qdrant/storage

    networks:
      - app-network

volumes:
  qdrant_storage:

networks:
  app-network:
